name: TS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 12.x

    steps:
      - name: Installing TypeScript
        run: npm install typescript
      - name: Installing Jest
        run: npm install --save-dev jest
      - name: Running Tests
        run: npm t
