name: TS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 12.x

    steps:
      - name: Checking out the Project's Code
        uses: actions/checkout@v2
      - name: Installing TypeScript
        run: npm ci
      - name: Compiling TypeScript Code
        run: tsc
      - name: Running Tests
        run: npm t
